// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_cova_is_on_fire = "CgkInJLw2NEXEAIQDg"; // <GPGSID>
        public const string leaderboard_normal_speedracer_highscore = "CgkInJLw2NEXEAIQAg"; // <GPGSID>
        public const string achievement_the_fake_one = "CgkInJLw2NEXEAIQBw"; // <GPGSID>
        public const string leaderboard_normal_tryhard_highscore = "CgkInJLw2NEXEAIQAw"; // <GPGSID>
        public const string achievement_vive_l_anr0k = "CgkInJLw2NEXEAIQCA"; // <GPGSID>
        public const string leaderboard_neo_speedracer_highscore = "CgkInJLw2NEXEAIQBQ"; // <GPGSID>
        public const string achievement_kakkate_koi_yo = "CgkInJLw2NEXEAIQDw"; // <GPGSID>
        public const string achievement_forget_the_worbu = "CgkInJLw2NEXEAIQDA"; // <GPGSID>
        public const string leaderboard_neo_normal_highscore = "CgkInJLw2NEXEAIQBA"; // <GPGSID>
        public const string achievement_under_the_line = "CgkInJLw2NEXEAIQEA"; // <GPGSID>
        public const string achievement_une_fabade_oh = "CgkInJLw2NEXEAIQCg"; // <GPGSID>
        public const string achievement_big_daddy = "CgkInJLw2NEXEAIQEg"; // <GPGSID>
        public const string achievement_collector = "CgkInJLw2NEXEAIQEQ"; // <GPGSID>
        public const string achievement_feel_the_rainbow = "CgkInJLw2NEXEAIQDQ"; // <GPGSID>
        public const string achievement_the_blacksmith = "CgkInJLw2NEXEAIQEw"; // <GPGSID>
        public const string leaderboard_normal_normal_highscore = "CgkInJLw2NEXEAIQAQ"; // <GPGSID>
        public const string achievement_niko_neko_ni = "CgkInJLw2NEXEAIQCQ"; // <GPGSID>
        public const string leaderboard_neo_tryhard_highscore = "CgkInJLw2NEXEAIQBg"; // <GPGSID>
        public const string achievement_time_to_revenge = "CgkInJLw2NEXEAIQCw"; // <GPGSID>

}

